version: "3.6"

services:
  node:
    build: .
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
    networks:
        - backend
  postgres:
    build:
      context: ./docker/postgres
    # To enable data persistence, uncomment the following lines
    # volumes:
    #   - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=default
    ports:
      - "5432:5432"
    networks:
        - backend

  redis:
    build:
      context: ./docker/redis
    # To enable data persistence, uncomment the following lines
    # volumes:
    #   - ./docker/redis/data:/data
    ports:
      - "6379:6379"

networks:
  backend:
    driver: bridge
