version: "3.6"

services:
  node:
    build: .
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    networks:
        - backend
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on: 
      - mongo
    networks:
      - backend

networks:
  backend:
    driver: bridge
